name: ClansPlugin
version: '1.0-SNAPSHOT'
main: org.plugin.clansPlugin.ClansPlugin
api-version: '1.20'


commands:
  clan:
    description: Основная команда управления кланами
    usage: /<command> <info|join|leave|chat|help|createbase|deletebase|setleader>
  chatcl:
    description: Отправить сообщение в клан-чат
    usage: /<command> <сообщение>
  clanchat:
    description: Переключить режим отправки сообщений в клан-чат
    usage: /<command> toggle

permissions:
  clan.admin:
    description: Право назначать лидера клана
    default: op

