name: ClansPlugin
version: '1.0-SNAPSHOT'
main: org.plugin.clansPlugin.ClansPlugin
api-version: '1.20'

commands:
  clan:
    description: Основная команда управления кланами
    usage: /<command> <info|join|leave|chat|help|createbase|deletebase|setleader|removeleader>
  chatcl:
    description: Отправить сообщение в клан-чат
    usage: /<command> <сообщение>
  clanchat:
    description: Переключить режим отправки сообщений в клан-чат
    usage: /<command> toggle
  showbase:
    description: Показывает границы территории базы клана
    usage: /<command>
  addplayer:
    description: Добавить игрока в клан
    usage: /<command> <игрок> <клан>
    permission: clan.admin
    permission-message: У вас нет прав для этой команды.
  removeplayer:
    description: Удалить игрока из клана
    usage: /<command> <ник>
    permission: clan.admin
    permission-message: У вас нет прав для этой команды.
  votel:
    description: Проголосовать за участника клана
    usage: /<command> <ник>
  # опционально, если startvote отдельная команда
  startvote:
    description: Начать голосование за нового лидера клана (только для админа)
    usage: /<command> <клан>
    permission: clan.admin
    permission-message: У вас нет прав для этой команды.

  endvote:
    description: Досрочно завершить голосование за лидера клана
    usage: /endvote <клан>
    permission: clan.admin
    permission-message: У вас нет прав для этой команды.
permissions:
  clan.admin:
    description: Право выполнять админские команды клана
    default: op
