name: ClansPlugin
version: '1.0-SNAPSHOT'
main: org.plugin.clansPlugin.ClansPlugin
api-version: '1.20'

commands:
  clan:
    description: Команды кланов (info, leave, chat, help, createbase, setleader deletebase и др.)
    usage: /clan <info|leave|chat|help|createbase|setleader|deletebase>
  chatcl:
    description: Отправить сообщение в клан-чат
    usage: /chatcl <сообщение>
  clanchat:
    description: Включает/выключает режим клан-чата
    usage: /clanchat toggle
  setleader:
    description: Назначить лидера клана
    usage: /setleader <игрок> <клан>
    permission: clan.admin
